Style/IndentationWidth:
  # Number of spaces for each indentation level.
  Width: 4
Metrics/LineLength:
  Max: 90
  Enabled: false
Style/RedundantReturn:
  Enabled: false
Style/NestedTernaryOperator:
  Enabled: false
Metrics/MethodLength:
  Enabled: false